name: draftclub
description: AplicaciÃ³n oficial DraftClub âš½ â€” crea tu carta, gestiona tu perfil y compite en ligas.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dependencies:
  firebase_dynamic_links: ^6.0.10

  flutter:
    sdk: flutter


  google_maps_flutter: ^2.14.0
  url_launcher: ^6.3.0

  # ðŸ§  Animaciones
  flutter_animate: ^4.5.0
  lottie: ^3.1.2

  visibility_detector: ^0.4.0

  # ðŸ”¥ Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3

  # ðŸ“· ImÃ¡genes
  image_picker: ^1.1.2
  image: ^4.2.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.2

  # Sonido

  audioplayers: ^6.1.0


  # ðŸ’… Fuentes y estado
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/draftclublogo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/draftclublogo.png"
